# Generated by Django 3.1 on 2020-08-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dewei',
            field=models.BooleanField(default=True),
        ),
    ]
