# Generated by Django 3.1 on 2020-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_question_dewei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('superpower', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
